[package]
name = "type-safe-builder-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.34"
syn = "2.0.44"
proc-macro2 = "1.0.73"
